import { ToolResourceContent } from '../../../../shared/components/tool-resource-content/tool-resource-content.types';

export const HTML_FORMATTER_RESOURCE_CONTENT: ToolResourceContent = {
  toolName: 'HTML',

  whatIsTitle: 'What is HTML?',
  whatIsBody: [
    'HTML (HyperText Markup Language) is the standard markup language used to structure content on the web. It describes a page using nested elements — tags like <div>, <p>, <img>, and <table> — that browsers parse and render into the layout, text, images, and interactive controls users see.',
    'HTML is forgiving by design: browsers try to render even malformed markup by auto-correcting missing tags or fixing bad nesting. That leniency is convenient for viewing pages, but it also means messy, inconsistent, or auto-generated HTML can accumulate over time — especially when it comes from a CMS, a minifier, a build tool, or copy-pasted snippets — making the underlying source hard to read and maintain.'
  ],

  whatIsToolTitle: 'What is an HTML Formatter?',
  whatIsToolBody: [
    'An HTML Formatter takes raw HTML — whether it\'s minified, inconsistently indented, or generated by a template engine — and rewrites it with clean, consistent indentation so the document structure and element nesting are easy to follow at a glance. It can also do the reverse: strip out unnecessary whitespace to shrink the markup for production use.',
    'This HTML Formatter beautifies markup with a configurable indent size, minifies HTML down to a compact form, and runs a basic structural validation pass — all inside a Monaco-powered editor with HTML syntax highlighting, running entirely in your browser. You can type or paste HTML directly, upload an .html/.htm file from disk, and copy or download the result when you\'re done.'
  ],

  whyUseTitle: 'Why Format HTML?',
  whyUseItems: [
    'Readability — consistent indentation makes it immediately obvious which elements are nested inside which, so you can trace a document\'s structure without counting brackets.',
    'Debugging markup — misplaced closing tags, broken nesting, and duplicated wrapper elements are far easier to spot once the HTML is properly indented.',
    'Cleaning up generated or minified HTML — output from CMSs, build pipelines, "view source," or third-party widgets often arrives as a single dense line; beautifying it makes it reviewable.',
    'Smaller payloads — minifying HTML strips comments-adjacent whitespace and collapses gaps between tags, reducing the size of the markup sent over the network.',
    'Cleaner diffs — formatting HTML consistently before committing it means code review and version control diffs highlight real changes instead of whitespace noise.'
  ],

  featuresTitle: 'Features of This Tool',
  features: [
    'Format (beautify) HTML with 2, 4, or 8-space indentation',
    'Minify HTML by collapsing whitespace between and around tags',
    'Basic HTML validation with a Valid/Invalid status badge',
    'Preserves the literal content of <pre>, <code>, and <textarea> elements instead of re-indenting it',
    'Monaco-powered editor with HTML syntax highlighting for both input and output',
    'Upload an .html or .htm file directly from disk',
    'Copy input or output HTML to the clipboard in one click',
    'Download the formatted result as a .html file',
    'Load a built-in sample document to try the tool instantly',
    'Runs entirely in your browser — your markup is never uploaded to a server'
  ],

  howToTitle: 'How to Use the HTML Formatter',
  howTo: [
    { title: 'Add your HTML', description: 'Paste HTML into the input editor, type it directly, upload an .html or .htm file, or click "Sample" to load a ready-made example.' },
    { title: 'Choose an indentation size', description: 'Pick 2, 4, or 8 spaces from the "Indentation" dropdown in the Actions panel — this controls how nested elements are indented when formatting.' },
    { title: 'Format, minify, or validate', description: 'Click "Format / Beautify HTML" to pretty-print the markup, "Minify HTML" to compact it, or "Validate HTML" to check its structure and get a formatted result if it parses cleanly.' },
    { title: 'Review the result', description: 'The output editor shows the resulting HTML along with a Valid/Invalid badge and a status message describing what happened.' },
    { title: 'Copy or download', description: 'Use "Copy Output" to copy the result to your clipboard, or "Download HTML" to save it as a .html file.' }
  ],

  commonErrorsTitle: 'Common HTML Errors and Pitfalls',
  commonErrors: [
    { title: 'Unclosed or mismatched tags', description: 'Forgetting a closing tag, or closing elements out of order (e.g. <b><i>text</b></i>), doesn\'t always throw a hard error — browsers silently repair the structure — but it can leave elements nested differently than you intended. Formatting the HTML makes mismatched nesting visible as unexpected indentation.' },
    { title: 'Closing void elements', description: 'Void elements like <br>, <img>, <input>, <hr>, and <meta> never have a closing tag or wrap content. Writing <br></br> or <img src="x.png"></img> is unnecessary and can confuse the formatter\'s indentation of surrounding content.' },
    { title: 'Unescaped special characters', description: 'Literal &, <, or > characters inside text content should be written as &amp;, &lt;, and &gt;. An unescaped & (e.g. "Terms & Conditions") or a stray < can be misread as the start of an entity or a tag.' },
    { title: 'Unquoted or space-containing attribute values', description: 'Attribute values that contain spaces must be quoted. class=foo bar is parsed as two separate attributes (class="foo" and bar), not a class with two words — it must be class="foo bar".' },
    { title: 'Duplicate attributes on one element', description: 'If the same attribute (e.g. class or id) appears twice on one tag, only the first occurrence is used by the browser; the duplicate is silently ignored rather than flagged as an error.' },
    { title: '"Valid" doesn\'t mean best-practice markup', description: 'Validation here checks that the document can be structurally parsed, not that it follows semantic HTML rules. Browsers parse HTML very leniently and auto-correct most structural problems, so severely malformed markup can still come back "Valid" after being silently repaired.' }
  ],

  examplesTitle: 'HTML Formatting Examples',
  examples: [
    {
      title: 'Minified to formatted',
      description: 'A dense, single-line HTML document beautified with 2-space indentation so the structure is easy to follow.',
      input: '<!DOCTYPE html><html><head><title>Demo</title></head><body><header><h1>Hello</h1></header><main><p>Welcome to our site.</p></main></body></html>',
      output: '<!DOCTYPE html>\n<html>\n<head>\n  <title>Demo</title>\n</head>\n<body>\n  <header>\n    <h1>Hello</h1>\n  </header>\n  <main>\n    <p>Welcome to our site.</p>\n  </main>\n</body>\n</html>'
    },
    {
      title: 'Formatted to minified',
      description: 'Indented HTML compacted with "Minify HTML." Note that this is a lightweight, regex-based minifier: it collapses whitespace runs and the gaps directly between tags, but it does not strip spaces that sit inside text content.',
      input: '<div>\n  <p>\n    Hello, world!\n  </p>\n</div>',
      output: '<div><p> Hello, world! </p></div>'
    },
    {
      title: 'Preserving <pre> content while formatting',
      description: 'Code blocks and other preformatted content inside <pre> are left exactly as written — including their internal line breaks and spacing — while the surrounding tags are still indented normally.',
      input: '<div><pre>\n  function add(a, b) {\n    return a + b;\n  }\n</pre></div>',
      output: '<div>\n  <pre>\n  function add(a, b) {\n    return a + b;\n  }\n</pre>\n</div>'
    }
  ],

  faqTitle: 'Frequently Asked Questions',
  faq: [
    { question: 'Is my HTML uploaded anywhere?', answer: 'No. This tool runs entirely client-side in your browser using a Monaco editor and a local formatting library. Your markup never leaves your device or gets sent to a server.' },
    { question: 'What\'s the difference between formatting and minifying HTML?', answer: 'Formatting (beautifying) adds consistent indentation and line breaks so the document structure is easy to read. Minifying collapses whitespace between and around tags to shrink the markup for production, at the cost of readability.' },
    { question: 'Why does my HTML show as "Valid" even though I think it has a mistake?', answer: 'HTML validation here uses the browser\'s built-in HTML parser, which is intentionally lenient — it auto-corrects many structural issues (like unclosed or mismatched tags) instead of rejecting them, the same way a browser would when rendering the page. This checks that the document can be parsed, not that it follows best practices.' },
    { question: 'Will formatting or minifying change how my page looks in the browser?', answer: 'No. Browsers already collapse whitespace between HTML tags when rendering (except inside <pre> and <textarea>), so adding or removing that whitespace does not change the rendered output — it only changes the readability of the source.' },
    { question: 'Does the formatter re-indent code inside <pre>, <code>, or <textarea>?', answer: 'No. Content inside these elements is treated as preformatted and preserved exactly as written, since whitespace inside them is often meaningful (for example, indentation in a code sample).' },
    { question: 'What indentation sizes are supported?', answer: '2, 4, or 8 spaces, selectable from the Indentation dropdown in the Actions panel. This applies to "Format / Beautify HTML" and to the formatted output produced by "Validate HTML."' },
    { question: 'What file types can I upload?', answer: 'You can upload .html or .htm files. The contents are loaded directly into the input editor for formatting, minifying, or validation.' }
  ]
};
